import { unitPrice } from './unitExposure.mjs';
import { loadPublicDataset, readJson, rowFromData } from "./calculate.mjs";

function fmtUsd(n) {
  if (!(n > 0)) return "—";
  if (n >= 1e12) {
    const t = n / 1e12;
    return `$${trimNum(t)}T`;
  }
  if (n >= 1e9) {
    const b = n / 1e9;
    return `$${trimNum(b)}B`;
  }
  if (n >= 1e6) {
    const m = n / 1e6;
    return `$${trimNum(m)}M`;
  }
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

function trimNum(n) {
  if (Number.isInteger(n)) return String(n);
  const s = n.toFixed(6).replace(/0+$/, "").replace(/\.$/, "");
  return s;
}

function fmtShares(n) {
  return Math.round(n).toLocaleString("en-US");
}

function fmtPrice(n) {
  return `$${n.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 4,
  })}`;
}

function fmtPer100(n) {
  return `$${n.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function col(value, width = 14) {
  return String(value).padEnd(width);
}

export const WORKED_EXAMPLE_TICKER = "DXYZ";
export const WORKED_EXAMPLE_LEG = "anthropic";

export function dxyzAnthropicWorkedExample(
  dataset = loadPublicDataset(),
  fixtures = readJson("reference/fixtures.json")
) {
  const raw = dataset.wrappers.find((w) => w.ticker === WORKED_EXAMPLE_TICKER);
  if (!raw?.anthropic) throw new Error("DXYZ Anthropic leg missing from data/");
  const row = rowFromData(raw, dataset.marks, fixtures);
  const leg = raw.anthropic;
  const exposure = row.anthPct;
  const shares = row.wrapperValue / row.price;
  const markPerUnit = leg.filedUnits > 0 ? leg.reportedFairValue / leg.filedUnits : null;
  const per100 = row.anthPer100;
  const fdShares = fixtures.anthFdShares;
  const scenarioPps = unitPrice({ valuation: fixtures.anthVal, fdShares, dilution: fixtures.dilution });
  const navSens = leg.filedUnits / shares;
  const filing = raw.filedSnapshot?.filingType || "filing";
  return {
    ticker: raw.ticker,
    basis: leg.basis,
    reportedFairValue: leg.reportedFairValue,
    fairValueAsOf: leg.fairValueAsOf,
    filingType: filing,
    filedUnits: leg.filedUnits,
    markPerUnit,
    impliedExposure: exposure,
    fdShares,
    scenarioPps,
    shares,
    price: row.price,
    wrapperValue: row.wrapperValue,
    per100,
    navSens,
    per100Label: fmtPer100(per100),
    fvLabel: fmtUsd(leg.reportedFairValue),
    unitsLabel: fmtShares(leg.filedUnits),
    markLabel: fmtPrice(markPerUnit),
    denomLabel: fmtUsd(row.wrapperValue),
    sharesLabel: fmtShares(shares),
    priceLabel: fmtPrice(row.price),
    navSensLabel: `$${navSens.toFixed(6)}`,
  };
}

export function renderWorkedExampleMarkdown() {
  const ex = dxyzAnthropicWorkedExample();
  return `<!-- BEGIN GENERATED: worked-example -->
*(regenerated by \`npm run sync:readme\` — do not hand-edit)*

**${ex.ticker} — Anthropic leg**

\`\`\`
basis:                    ${ex.basis}
filedUnits:               ${col(ex.unitsLabel)}
reportedFairValue:        ${col(ex.fvLabel)} (as of ${ex.fairValueAsOf}, ${ex.filingType})
→ markPerUnit:            ${col(ex.markLabel)} (computed, not stored)
→ estimated FD shares:    ${fmtShares(ex.fdShares)} (adjustable calibration proxy, not filed)
→ scenario price:         ${fmtPrice(ex.scenarioPps)} = valuation × (1 − dilution) ÷ estimated FD shares
→ scenario exposure:      ${(ex.impliedExposure * 100).toPrecision(8)}% (units ÷ estimated FD shares)

ΔNAV per $1 PPS:          ${col(ex.navSensLabel)} (${ex.unitsLabel} ÷ ${ex.sharesLabel})
denominator:              ${col(ex.denomLabel)} (market-cap: ${ex.sharesLabel} sh × ${ex.priceLabel})

${ex.unitsLabel} × ${fmtPrice(ex.scenarioPps)} ÷ ${ex.denomLabel} × $100  =  ${ex.per100Label} per $100
\`\`\`

*(${ex.priceLabel} from \`reference/fixtures.json\` — frozen prices dated August 19 with the September 5 dataset, not a historical backtest. Filed Holdings; both valuation and FD controls revalue this row. Display digits are rounded; calculation uses full precision.)*
<!-- END GENERATED: worked-example -->`;
}
