import {
  impliedExposure,
  lookThroughPer100,
  markById,
  markPostMoney,
} from "./derive.mjs";
import { loadPublicDataset, readJson, rowFromData } from "./calculate.mjs";

function fmtUsd(n) {
  if (!(n > 0)) return "—";
  if (n >= 1e12) {
    const t = n / 1e12;
    return `$${trimNum(t)}T`;
  }
  if (n >= 1e9) {
    const b = n / 1e9;
    return `$${trimNum(b)}B`;
  }
  if (n >= 1e6) {
    const m = n / 1e6;
    return `$${trimNum(m)}M`;
  }
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

function trimNum(n) {
  if (Number.isInteger(n)) return String(n);
  const s = n.toFixed(6).replace(/0+$/, "").replace(/\.$/, "");
  return s;
}

function fmtPctFromFraction(frac) {
  const pct = frac * 100;
  if (pct >= 1) return `${pct.toFixed(2)}%`;
  if (pct >= 0.1) return `${pct.toFixed(3)}%`;
  return `${pct.toPrecision(6)}%`;
}

function fmtShares(n) {
  return Math.round(n).toLocaleString("en-US");
}

function fmtPrice(n) {
  return `$${n.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 4,
  })}`;
}

function fmtPer100(n) {
  return `$${n.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function col(value, width = 14) {
  return String(value).padEnd(width);
}

export const WORKED_EXAMPLE_TICKER = "DXYZ";
export const WORKED_EXAMPLE_LEG = "anthropic";

export function dxyzAnthropicWorkedExample(
  dataset = loadPublicDataset(),
  fixtures = readJson("reference/fixtures.json")
) {
  const raw = dataset.wrappers.find((w) => w.ticker === WORKED_EXAMPLE_TICKER);
  if (!raw?.anthropic) throw new Error("DXYZ Anthropic leg missing from data/");
  const row = rowFromData(raw, dataset.marks, fixtures);
  const leg = raw.anthropic;
  const mark = markById(dataset.marks, leg.measurementCompanyMark);
  const scenario = markById(dataset.marks, dataset.marks.lastPrimary.anthropic);
  const exposure = impliedExposure(leg, dataset.marks);
  const shares = row.wrapperValue / row.price;
  const per100 = lookThroughPer100({
    claimPct: exposure,
    ipoVal: fixtures.anthVal,
    wrapperValue: row.wrapperValue,
    dilution: fixtures.dilution,
  });
  const pctLabel = fmtPctFromFraction(exposure);
  const filing = raw.filedSnapshot?.filingType || "filing";
  return {
    ticker: raw.ticker,
    basis: leg.basis,
    reportedFairValue: leg.reportedFairValue,
    fairValueAsOf: leg.fairValueAsOf,
    filingType: filing,
    measurementPostMoney: markPostMoney(dataset.marks, leg.measurementCompanyMark),
    measurementName: mark?.name,
    measurementClosed: mark?.closed,
    impliedExposure: exposure,
    scenarioPostMoney: scenario?.postMoney,
    scenarioName: scenario?.name,
    scenarioClosed: scenario?.closed,
    shares,
    price: row.price,
    wrapperValue: row.wrapperValue,
    per100,
    pctLabel,
    per100Label: fmtPer100(per100),
    fvLabel: fmtUsd(leg.reportedFairValue),
    markLabel: fmtUsd(markPostMoney(dataset.marks, leg.measurementCompanyMark)),
    scenarioLabel: fmtUsd(scenario?.postMoney),
    denomLabel: fmtUsd(row.wrapperValue),
    sharesLabel: fmtShares(shares),
    priceLabel: fmtPrice(row.price),
  };
}

export function renderWorkedExampleMarkdown() {
  const ex = dxyzAnthropicWorkedExample();
  const closed = ex.measurementClosed ? `, ${ex.measurementClosed}` : "";
  const scenarioClosed = ex.scenarioClosed ? `, ${ex.scenarioClosed}` : "";
  return `<!-- BEGIN GENERATED: worked-example -->
*(regenerated by \`npm run sync:readme\` — do not hand-edit)*

**${ex.ticker} — Anthropic leg**

\`\`\`
basis:                    ${ex.basis}
reportedFairValue:        ${col(ex.fvLabel)} (as of ${ex.fairValueAsOf}, ${ex.filingType})
measurementCompanyMark:   ${col(ex.markLabel)} (${ex.measurementName}${closed})
→ impliedExposure:        ${col(ex.pctLabel)} (computed, not stored)

scenario valuation:       ${col(ex.scenarioLabel)} (Anthropic ${ex.scenarioName}${scenarioClosed})
denominator:              ${col(ex.denomLabel)} (market-cap: ${ex.sharesLabel} sh × ${ex.priceLabel})

${ex.pctLabel} × ${ex.scenarioLabel} ÷ ${ex.denomLabel} × $100  =  ${ex.per100Label} per $100
\`\`\`

*(${ex.priceLabel} and scenario marks from \`reference/fixtures.json\` — frozen for reproducibility, not live quotes.)*
<!-- END GENERATED: worked-example -->`;
}
